### ISSUE TITLE
Fan Threshold

### ISSUE THREAD

**Issue by cronopsxploit** [Hakkuraifu/PS4xploit#1]
please friend if you are not going to ask for a lot of six who is a very busy guy who is doing a great job, would you like to implement the Fan Threshold function, and set the temperature to 73ºC or else make the user choose the temperature?
I used the "darkmoddervc" and it is set to 60ºC because of that now my ps4 is looking like an airplane every time I enter a game.
help me T_T

**Comment by Nazky** [comment]
i can make a fix for that i think

**Comment by Nazky** [comment]
it's normally fix you can now deactivate the payload
