### ISSUE TITLE
Goldhen V1.1 freeze the system when try to poweroff 

### ISSUE THREAD

**Issue by nalawneh-co** [Hakkuraifu/PS4xploit#10]
I'm on 7.50 firmware and when I try to shutdown my device during using Goldhen V1.1, the ps4 freeze for 1 minute and then make a beep sound then closed, but when I turn it on again the ps4 run normally without display the HD check screen.

Note: The are no issue with restart function, it restart the device normally.

PS4 version is slim.

Thank you.

**Comment by Nazky** [comment]
it's a goldhen issue so you need to report this bug to sistro also if you can is recommend to update to 7.55 (more stable)
