### ISSUE TITLE
Please add other Linux loader for 7.02

### ISSUE THREAD

**Issue by justguyongithub** [Hakkuraifu/PS4xploit#3]
Hi
Linux loader which you added don't work for me (the system cannot be installed, the system cannot be started. When trying to install it refers to "invalid argument" (something like that...).
When trying to start the system, the file system is not mounted, kernel modules are not loaded (something like that, as I understand it).

Only this Linux loader works for me - https://twitter.com/Cedsaill2/status/1341594906381475845 (ONLY **PS4-Linux-Loader_normalEDID.bin**, which is inside the archive)
PS4 Slim CUH-2008A
Kernel 4.14.93 (only this kernel works for me)

So, could you add this payload to your host? Nobody hosts this payload...

**Comment by Nazky** [comment]
i have add the Linux-1GBVRAM payload you can test

**Comment by justguyongithub** [comment]
Very bad:
1GB VRAM - just no image.
3GB VRAM - image have, but system cannot start.

Why don't you just use the payloads I dropped for you? - https://twitter.com/Cedsaill2/status/1341594906381475845
In archive:
PS4-Linux-Loader.bin - this 3GB VRAM
PS4-Linux-Loader_normalEDID.bin - this 1GB VRAM
For me works great, but nobody hosts these payloads (possibly other than 3GB VRAM, but for a Linux installation, 3GB VRAM is not the best option - the system may not install because of this, although after installation the system starts).

**Comment by justguyongithub** [comment]
if you're use payloads sleirsgoevy - so, strange, why don't work 3GB VRAM...

**Comment by justguyongithub** [comment]
I can make the next test only after 10-11 hours

**Comment by Nazky** [comment]
i litteraly use the bin you drop for the 1 GB VRAM and convert it to js so yeah it's the same i have test it on my slim and it work

**Comment by justguyongithub** [comment]
This is very strange... Have you tested this by running from your host? Perhaps a mistake was made somewhere, I don't know ...
Linux loader on host sleirsgoevy works fine for me (only 3GB VRAM works there now) - https://sleirsgoevy.github.io/ps4jb/index702.html (literally after testing, I launched linux loader on sleirsgoevy host to make sure that everything works fine for me - and, of course, everything works)

**Comment by justguyongithub** [comment]
And, of course, the payloads that I threw off work fine for me too (I wait, I send requests until someone uploads them to the host)

**Comment by Nazky** [comment]
yes i have test and actually i run the payload for installing linux on my hdd so yeah it's work the 2 payloads work (and the payload 3GB VRAM is the same on my host and on sleirsgoevy)

**Comment by justguyongithub** [comment]
You also test run payloads from your host, right? If so, then this is strange... I'll check later again...

> (and the payload 3GB VRAM is the same on my host and on sleirsgoevy)
And how can this be?... On the host sleirsgoevy I run 3GB VRAM - it works, on your host I run 3GB VRAM - it does not work (to be precise, the system does not start, many errors). I am using SSD.

**Comment by Nazky** [comment]
do you use the right bzimage ?

**Comment by justguyongithub** [comment]
Problem is not that.
Only kernel 4.14.93 works for me, so no options (+ everything is checked several times by MD5 for integrity).

I send these payloads via my computer - everything works is stable and without any problems. I try to run it through your host - nothing works (as I wrote above). I run it through the sleirsgoevy host - it works the same without problems and is stable (but at the moment only 3GB VRAM works there).

I have been using Linux for 7+ hours (via host sleirsgoevy) so problem is not that.

Before each launch of the Linux loader, I clear the cache and cookies.

**Comment by justguyongithub** [comment]
> (but at the moment only 3GB VRAM works there).

To be more precise, sleirsgoevy host has some kind of error in this regard:
1GB VRAM = 3GB VRAM
3GB VRAM = 3GB VRAM

**Comment by Nazky** [comment]
i don't know what to say i can't fix if there are no problem many people use my linux without problem i try several think but i have be able to install linux on hdd and it's work so i don't know the linux 3gb vram is the exact same and the 1gb vram work too it's not a host problem or a javascript problem

**Comment by justguyongithub** [comment]
I have tested now - great works (1GB VRAM and 3GB VRAM). Mystic =).
Thank you for promptness. And sorry for the inconvenience.

**Comment by Nazky** [comment]
np
