### ISSUE TITLE
REST mode not working 7.02

### ISSUE THREAD

**Issue by wpinacz** [Hakkuraifu/PS4xploit#5]
Hi,
is there a way to fully support REST mode?
When console goes to REST mode the yellow led blinks for a while and I hear HDD shuts down, then console shuts off, after turning on there's a message that the proper shutdown hasn't been used.

Thanks.

**Comment by Nazky** [comment]
i don't work on mira or hen so idk we need to wait a official update from mira or hen for fix the rest mode

**Comment by Nazky** [comment]
rest mode now working with hen 2.1.3b
